### ISSUE TITLE
Finish project setup

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr-gwt#1]
* [x] Connect to Travis-CI
* [x] Create a more mature README.md with badges etc.
* [x] Javaslang core build: Trigger javaslang-gwt when core build succeeded
* [x] split javaslang-gwt and javaslang-gwt-example into two repos
* [x] travis: after_success: mvn clean deploy -DskipTests --settings .travis/maven-settings.xml

**Note:** Moved the last steps to #4

**Comment by danieldietrich** [comment]
Build triggers: https://docs.travis-ci.com/user/triggering-builds

**Comment by danieldietrich** [comment]
Hi @ruslansennov,

I fiddled around a bit with the project today and want to get rid of the parent pom of this project.

These are the options:

1) have two repos javaslang-gwt and javaslang-gwt-example
2) have one repo and one project with a maven profile for the gwt-example

I favor the first, because the example is started manually. And does not need necessarily have to depend on the actual development branch of javaslang-gwt.

What do you think?

---

I also checked docs on how to setup a travis-ci trigger. Need to perform tests (locally).

The solution will contain a script `trigger-module.sh` (in javaslang core repo) that is called with parameter `javaslang-gwt`. So it will scale to trigger any kind of javaslang module in future.

The only thing is that I need to figure out the travis-ci token. I once have generated it I think but I'm not sure... Maybe I need to re-generate it...

**Comment by ruslansennov** [comment]
Hi

> I favor the first, because the example is started manually. And does not need necessarily have to depend on the actual development branch of javaslang-gwt.

Let's keep this in one repo for a while, as is. Our main goal is to make CI and snapshot/release deployments

**Comment by danieldietrich** [comment]
Ok, thank you!

I have problems with the travis access token within the Javaslang core project. The trigger-script works on my local machine - seems sth related to `travis encrypt` in conjunction with accessing environment variables on the CI server.

Will try to add an encrypted variable to the get project:

```bash
travis encrypt --org -r javaslang/javaslang-gwt 'TEST_KEY=TEST_VALUE'
```

And print that in an after_success step on the CI server to the console (just a test value):

```yaml
after_success:
  - echo "TEST_KEY: $TEST_KEY"
  - echo "env.TEST_KEY: ${env.TEST_KEY}"
  - echo "env.global.TEST_KEY: ${env.global.TEST_KEY}"
  - echo "global.TEST_KEY: ${global.TEST_KEY}"
```

**Update:** Interestingly the javaslang-gwt project shows the following:

<img width="460" alt="screen shot 2016-12-13 at 09 12 52" src="https://cloud.githubusercontent.com/assets/743833/21132506/ac67b898-c114-11e6-9720-606b3dc2ad8f.png">

But the Javaslang core project does not...

The only difference between the travis configurations (that I spot) is, that the javaslang-gwt project does not use double-quotes:

```yams
env:
  global:
    secure: ADb+...4v4CHKgIjlc=
```

The Javaslang core project config does use double-quotes:

```yaml
env:
  global:
    - secure: "HU0QOLEDk...NkM8l0="
    - secure: "VByzrX+iZ...ZN8hF4f5/V8="
    - secure: "GWvKpGPBF...1mVj4LI="
```

However, the output of the javaslang-gwt test-build was not successful:

<img width="955" alt="screen shot 2016-12-13 at 09 18 57" src="https://cloud.githubusercontent.com/assets/743833/21132623/49ed625c-c115-11e6-8c39-5366f6371ed9.png">

**Comment by danieldietrich** [comment]
Next try...

.travis.yml

```yams
after_success:
- ./test.sh
```

test.sh

```bash
#!/usr/bin/env bash

echo "TEST_KEY: $TEST_KEY"
echo "TEST_KEY: ${TEST_KEY}"
echo "env.TEST_KEY: ${env.TEST_KEY}"
echo "env.global.TEST_KEY: ${env.global.TEST_KEY}"
echo "global.TEST_KEY: ${global.TEST_KEY}"
```

**Update:** This test looks good:

<img width="959" alt="screen shot 2016-12-13 at 09 38 45" src="https://cloud.githubusercontent.com/assets/743833/21133208/07a5fd66-c118-11e6-892e-14bbb851b347.png">

**Comment by danieldietrich** [comment]
Still does not work. Message: wrong_credentials, access denied.

See also https://github.com/travis-ci/travis.rb/issues/340

**Comment by danieldietrich** [comment]
Huston, we have a problem 👀

it seems that the travis-ci env variables are not set at all in the javaslang project. At least I can't read them. I wrote a similar build config and test-script in the javaslang-gwt project and there it works 🤔

<img width="955" alt="screen shot 2016-12-13 at 13 41 51" src="https://cloud.githubusercontent.com/assets/743833/21140863/77388ec4-c13a-11e6-93a7-21da16f5e127.png">

In the above example `TEST: TEST_VALUE` should be printed but it is just `TEST:` because the env variable `TEST_KEY` seems to be not present.

**Comment by ruslansennov** [comment]
maybe we should ask help from travis developers?

**Comment by danieldietrich** [comment]
Yes, but before I will try sth later. Maybe we overwrite with .travis/ a default folder? Will check that... It is suspicious that the env vars aren't set at all.

**Comment by danieldietrich** [comment]
Indeed, the javaslang core does not seem to have env vars on the build server. These are the resulting/parsed configs on travis-ci.org:

## javaslang ("global_env": null)

![screen shot 2016-12-14 at 12 53 35](https://cloud.githubusercontent.com/assets/743833/21181143/bc63a41c-c1fc-11e6-9204-61895f9c6919.png)

## javaslang-gwt ("global_env": "TEST_KEY=[secure]")

![screen shot 2016-12-14 at 12 54 23](https://cloud.githubusercontent.com/assets/743833/21181168/de414eae-c1fc-11e6-8e4e-c456622cfeb0.png)

I will create further tests for setting up the env properly in the javaslang core project.

**Comment by danieldietrich** [comment]
I've checked the last master branch build of javaslang core. The env vars are present. I think the vars are gone on PR builds for security reasons.

I will clean up the [PR](https://github.com/javaslang/javaslang/pull/1758) and merge - it should already work 😊

![screen shot 2016-12-14 at 13 05 55](https://cloud.githubusercontent.com/assets/743833/21181436/3324122a-c1fe-11e6-8745-891d7cc8998b.png)

**Comment by danieldietrich** [comment]
Yep, there it is. Now waiting for the triggered get build ...

![screen shot 2016-12-14 at 13 54 25](https://cloud.githubusercontent.com/assets/743833/21182736/e5cae29a-c204-11e6-80c2-6f1934f27537.png)

**Comment by danieldietrich** [comment]
It does work :-)
