### ISSUE TITLE
GwtIIncompatible annotated io.vavr.collection.JavaConverters.ListView.toArray(U[]) breaks GWT compilation on depending modules

### ISSUE THREAD

**Issue by dharezlak** [vavr-io/vavr-gwt#10]
The error I get is the following:
`The type JavaConverters.ListView<T,C> must implement the inherited abstract method Collection<T>.toArray(T[])`.

I am not sure why this is happening as the method should be ignored by GWT compiler and not dropped completely.

Overwriting the class with an empty `toArray` implementation and removing the `@GwtIncompatible` annotation helps.

**Comment by dharezlak** [comment]
After a few more checks it turned out to be only the problem in the SDM (Super Dev Mode). When compiling the final JS everything works fine. This has been reported with https://github.com/gwtproject/gwt/issues/9526.

**Comment by ruslansennov** [comment]
@dharezlak also please see vavr-io/vavr-gwt-example#3 and vavr-io/vavr#1992

**Comment by ruslansennov** [comment]
fixed in last release
