### ISSUE TITLE
Future is now based on Executor instead of ExecutorService

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr-gwt#12]
My latest changes on Vavr's Future broke the build.
I will try to fix that...

<img width="1316" alt="screen shot 2017-12-28 at 17 28 55" src="https://user-images.githubusercontent.com/743833/34416648-bb23147a-ebf4-11e7-99f0-93d65f2ca323.png">

**Comment by danieldietrich** [comment]
On my machine a `mvn clean test` runs ok (it depends on 1.0.0-SNAPSHOT):

<img width="726" alt="screen shot 2017-12-28 at 17 36 35" src="https://user-images.githubusercontent.com/743833/34416876-e049c842-ebf5-11e7-8aa3-78f748d0d0bf.png">

@ruslansennov the vavr-gwt/src/main/resources/**/* stuff seems fragile to me. I would suggest to exclude the whole io.vavr.concurrent package from vavr-gwt. Does Multithreading make sense in the GWT part of a Javascript application?

The super.io.vavr.concurrent.FutureImpl seems to be outdated. Do we have to copy/paste the source all the time when we make changes to Vavr's FutureImpl? How do we know which dependencies need to be included as part of the super package for GWT? And how do we know if we can remove dependencies again, when they are not needed anymore?

This all seems a bit fragile to me 🤔

**Comment by ruslansennov** [comment]
`super.io.vavr.concurrent.FutureImpl` must have the same signatures as `io.vavr.concurrent.FutureImpl`. I'll try to fix it soon.

**Comment by danieldietrich** [comment]
Great, thx!
Would it be worth to automatically extract these from source jars as part of the build process? Then it would be always actual.

**Comment by ruslansennov** [comment]
> Would it be worth to automatically extract these from source jars as part of the build process? Then it would be always actual.

I think it s too complicated...  In addition to copying, there is still a lot to be changed

**Comment by ruslansennov** [comment]
> Does Multithreading make sense in the GWT part of a Javascript application?

I'm not familiar with js, but I can image an exotic situation when `Future` is very useful. It could be the implementation of `Executor` on workers (is it possible?). `Future` will be still single threaded, but asynchronous.

**Comment by danieldietrich** [comment]
Yes, Javascript has a notion for async processing. It is Promise in ES6, similar to our Future. In ES7 there is also an async keyword.
