### ISSUE TITLE
OOME: Java heap space

### ISSUE THREAD

**Issue by ruslansennov** [vavr-io/vavr-gwt#6]
gwt compilation fails after increasing tuples arity (I guess, (see javaslang/javaslang/pull/1848))
hope this is gwt-compiler problems
/cc @danieldietrich @paplorinc

**Comment by danieldietrich** [comment]
Is it possible to increase max heap space using maven args?

**Comment by l0rinc** [comment]
hmmm, what's the error for https://travis-ci.org/javaslang/javaslang-gwt exactly?

**Comment by ruslansennov** [comment]
I tried to increase memory limit to 4g but compilation fails again. It seems we should annotate with `@GwtIncompatible` all methods with arity greater than 8 (for a while or forever). I'll prepare PR if there is no other opinions.

```xml
<configuration>
  <testTimeOut>0</testTimeOut>
  <extraJvmArgs>-Xmx4g</extraJvmArgs>
  <productionMode>true</productionMode>
</configuration>
```

>  what's the error for ... exactly?

@paplorinc tests fails with error message after few hours of working (on my $work computer). Unfortunately, I did not record the error accurately

**Comment by ruslansennov** [comment]
Annotations have not helped. 
Tests pass only with artifact that was build at previous commit (CharSeq.repeat speedup a5fb82)

**Comment by l0rinc** [comment]
@ruslansennov, how can I help?

**Comment by ruslansennov** [comment]
I don't know. I'm afraid googlers will do nothing about this extremal case (a LOT of methods and arity). I see  only two possibilities: revert last commit or remove gwt support

**Comment by l0rinc** [comment]
Are you sure it's the arity? Could you make the tests tell a verdict of what's wrong?

**Comment by ruslansennov** [comment]
Could you verify me please? My observations are: with latest javaslang's snapshot tests fails with OOME after very long time of work; with snapshot builded at previous commit all works fine.
I don't remember exactly, but stacktrace shows the classes related to JdtCompiler

**Comment by l0rinc** [comment]
Sure, will check it out tomorrow :)

**Comment by l0rinc** [comment]
I'm trying to run the build with a reverted Javaslang, but changing the main `pom` to
```xml
<dependency>
    <groupId>${project.groupId}</groupId>
    <artifactId>javaslang</artifactId>
    <version>${project.version}</version>
    <scope>system</scope>
    <systemPath>(...)/javaslang/javaslang/target/javaslang-2.1.0-SNAPSHOT.jar</systemPath>
</dependency>
<dependency>
    <groupId>${project.groupId}</groupId>
    <artifactId>javaslang</artifactId>
    <version>${project.version}</version>
    <classifier>sources</classifier>
    <scope>system</scope>
    <systemPath>(...)/javaslang/javaslang/target/javaslang-2.1.0-SNAPSHOT-sources.jar</systemPath>
</dependency>
<dependency>
    <groupId>${project.groupId}</groupId>
    <artifactId>javaslang-match</artifactId>
    <version>${project.version}</version>
    <classifier>sources</classifier>
    <scope>system</scope>
    <systemPath>(...)/javaslang/javaslang-match/target/javaslang-match-2.1.0-SNAPSHOT-sources.jar</systemPath>
</dependency>
```
does't seem to be enough, the tests still hang.
Any advice?

**Comment by ruslansennov** [comment]
I'm not familiar with maven, so yesterday I just removed all javaslang artifacts in `.m2` folder, created reverted javaslang and then all tests passed within about 5 minutes

**Comment by l0rinc** [comment]
there seems to be some internal limit, but can't find the source. Will revert the 10 to 8 :(

**Comment by ruslansennov** [comment]
Thank you

**Comment by l0rinc** [comment]
https://github.com/javaslang/javaslang/pull/1857
